### ISSUE TITLE
Create sequence diagram for bookmarking

### ISSUE THREAD

**Issue by zbuseaydin** [bounswe/bounswe2024group4#112]
### Issue Type

Deliverable

### Issue Description

Create and add the relevant diagrams in the [sequence diagrams page](https://github.com/bounswe/bounswe2024group4/wiki/Sequence-Diagrams).

**Comment by fatih260** [comment]
This issue is a duplicate of this closed [issue](https://github.com/bounswe/bounswe2024group4/issues/115)
