### ISSUE TITLE
Create sequence diagram for Wikidata API requirement

### ISSUE THREAD

**Issue by zbuseaydin** [bounswe/bounswe2024group4#114]
### Issue Type

Deliverable

### Issue Description

Create and add the relevant diagrams in the [sequence diagrams page](https://github.com/bounswe/bounswe2024group4/wiki/Sequence-Diagrams). Case: view player/team page that is not in our cache

**Comment by ceyhunsonyurek** [comment]
Added [here](https://github.com/bounswe/bounswe2024group4/wiki/Sequence-Diagrams#wikidata-api)
