### ISSUE TITLE
Implement profile page

### ISSUE THREAD

**Issue by zbuseaydin** [bounswe/bounswe2024group4#193]
### Issue Type

Feature Request

### Issue Description

Implement the profile page in mobile so that the info is displayed.

**Comment by nucan25** [comment]
Mobile Profile page to display user information. The Profile component retrieves the user data, including username, profile picture, bio, and counts for posts, followers, and following. Additionally, there's a button to navigate to the Edit Profile screen.  https://github.com/bounswe/bounswe2024group4/pull/277
