### ISSUE TITLE
Implement search results page

### ISSUE THREAD

**Issue by zbuseaydin** [bounswe/bounswe2024group4#223]
### Issue Type

Feature Request

### Issue Description

After searching, there must exist a search results page in mobile that shows the results of the search. The user must be redirected to the relevant pages.

**Comment by nucan25** [comment]
Implemented the SearchResults component to display search results for teams, players. Users can navigate to the respective team or player details by tapping on the results.  
 https://github.com/bounswe/bounswe2024group4/pull/276
