### ISSUE TITLE
Create user tests

### ISSUE THREAD

**Issue by zbuseaydin** [bounswe/bounswe2024group4#251]
### Issue Type

Deliverable

### Issue Description

User tests should be created with the mobile screenshots.

**Comment by zbuseaydin** [comment]
i created these tests:
[Mobile Test Case 001](https://github.com/bounswe/bounswe2024group4/wiki/Mobile-TC001-%E2%80%90-Sign-Up)
[Mobile Test Case 002](https://github.com/bounswe/bounswe2024group4/wiki/Mobile-TC002%E2%80%90--Log-In)
[Mobile Test Case 006](https://github.com/bounswe/bounswe2024group4/wiki/Mobile-TC006-%E2%80%90-Like-Post)
[Mobile Test Case 008](https://github.com/bounswe/bounswe2024group4/wiki/Mobile-TC008-%E2%80%90-Comment)
[Mobile Test Case 009](https://github.com/bounswe/bounswe2024group4/wiki/Mobile-TC009-%E2%80%90-Create-Post)

**Comment by nucan25** [comment]
User tests for search and profile editing have been completed. #317

**Comment by talhaordukaya** [comment]
I created user tests. [#314](https://github.com/bounswe/bounswe2024group4/issues/314)
