### ISSUE TITLE
Create user tests for frontend

### ISSUE THREAD

**Issue by berat-yilmaz** [bounswe/bounswe2024group4#252]
### Issue Type

Deliverable

### Issue Description

User tests should be created with the frontend screenshots.

**Comment by batuhancanli0** [comment]
- [ ] Sign Up 
- [ ] Login 
- [ ] Create a Post
- [ ] See Other's Profile
- [ ] Follow/Unfollow
- [ ] Post Like
- [ ] Comment
- [ ] Post Bookmark
- [ ] Comment Like
- [ ] Search
- [ ] Edit Profile

**Comment by batuhancanli0** [comment]
I created user tests for login,create post,edit profile and bookmark

**Comment by ceyhunsonyurek** [comment]
I created user tests for sign up, see other's profile, follow/unfollow, comment like, and search
