### ISSUE TITLE
Create sequence diagrams of deletion actions

### ISSUE THREAD

**Issue by zbuseaydin** [bounswe/bounswe2024group4#350]
### Issue Type

Bug Report

### Issue Description

Sequence diagrams of the following actions should be created:

- [x] Delete Post
- [x] Delete Exercise Program (same with other deletes)
- [x] Delete Diet Program
- [x] Delete Comment

**Comment by nucan25** [comment]
The sequence diagrams for deletion actions were created [here.](https://github.com/bounswe/bounswe2024group4/wiki/Sequence-Diagrams:-Fitness-and-Diet-Forum#deletion-actions)
