### ISSUE TITLE
Create sequence diagram for Wikidata and Nutrition Analysis API Integration

### ISSUE THREAD

**Issue by kaanguneyli** [bounswe/bounswe2024group4#356]
### Issue Type

Deliverable

### Issue Description

Sequence diagram of creating new food options (covers Wikidata and Nutrition Analysis API integration) should be created

**Comment by zbuseaydin** [comment]
done https://github.com/bounswe/bounswe2024group4/wiki/Sequence-Diagrams:-Fitness-and-Diet-Forum#create-food-in-a-meal
