### ISSUE TITLE
Create post component

### ISSUE THREAD

**Issue by zbuseaydin** [bounswe/bounswe2024group4#364]
### Issue Type

Feature Request

### Issue Description

Implement post component in frontend. Put static posts in home page.

**Comment by zbuseaydin** [comment]
this can be helpful: https://github.com/bounswe/bounswe2024group4/blob/main/archive/frontend/src/components/Post.js

**Comment by ozturkMirac** [comment]
The feature request to implement the post component in the frontend with static posts on the home page has been addressed. PR #387 introduces the Post component with dynamic user details, a scrollable meal list, and post actions, integrated into the PostPage. Closing this issue as the required functionality has been implemented.
