### ISSUE TITLE
Perform an analysis of NBA-related software systems

### ISSUE THREAD

**Issue by berat-yilmaz** [bounswe/bounswe2024group4#45]
### Issue Type

Wiki

### Issue Description

We need to document our observations on the NBA-related software systems' missing features and keep a list of them.

**Comment by kaanguneyli** [comment]
Created the [page](https://github.com/bounswe/bounswe2024group4/wiki/Similar-Projects), just need to check the description to make sure that what is created covers what is expected

**Comment by kaanguneyli** [comment]
Done
