### ISSUE TITLE
Create sequence diagrams related to posts

### ISSUE THREAD

**Issue by fatih260** [bounswe/bounswe2024group4#76]
### Issue Type

Deliverable

### Issue Description

Create sequence diagrams of viewing own profile and editing profile which are under ["Post"](https://github.com/bounswe/bounswe2024group4/wiki/Sequence-Diagrams#post) using mermaid.

**Comment by fatih260** [comment]
I did the first two of them and they can be seen [here](https://github.com/bounswe/bounswe2024group4/wiki/Sequence-Diagrams#post).

**Comment by ceyhunsonyurek** [comment]
I added "Like a Post" and "View a Post (with its Comments)" sequence diagrams [here](https://github.com/bounswe/bounswe2024group4/wiki/Sequence-Diagrams#like-a-post)
