### ISSUE TITLE
Create sequence diagrams related to user activities

### ISSUE THREAD

**Issue by berat-yilmaz** [bounswe/bounswe2024group4#81]
### Issue Type

Deliverable

### Issue Description

Create and add the relevant diagrams to the search part in the [sequence diagrams page](https://github.com/bounswe/bounswe2024group4/wiki/Sequence-Diagrams).

**Comment by ceyhunsonyurek** [comment]
Added sequence diagrams related to user interactions [here](https://github.com/bounswe/bounswe2024group4/wiki/Sequence-Diagrams#user-interactions)
