### ISSUE TITLE
Fix the problems in user requirements

### ISSUE THREAD

**Issue by zbuseaydin** [bounswe/bounswe2024group4#95]
### Issue Type

Bug Report

### Issue Description

Fix the problems in the [user requirements](https://github.com/bounswe/bounswe2024group4/wiki/Requirements#11-user-requirements) according to the feedback given.

### Additional Context

Feedback:

### User Requirements
- You have already defined user, guest, and member, so there's no need to repeat a requirement like the one below. Instead, you can (and should) list common requirements for users and then specify the necessary requirements for guests and members separately.
1.1.1.3.1 Members shall be able to do all the activities listed in the 1.1.2.1 Guest activities section.

- However, you need to be careful when using these terms.
1.1.3.2.3 Members should be able to like and comment on other member posts, and should be able to like other user's comments.

- I believe you should have used shall instead of should. These are not optional.
1.1.3.2.4 Member should be able to delete their posts and comments.
1.1.3.2.5 Members should be able to follow other members.

- Instead of writing complex requirements, it is better to break them down into separate requirements and list them.
1.1.1.2.3 Members should be able to control their privacy settings, such as who can see their posts and profile information (e.g., public, friends only), whether their profile appears in search results, Ability to block other users.
 
- You should not define how
1.1.2.1.3 Guests shall be able to access the user posts through the main page.

- If a member can follow another member, he/she can unfollow the member or can view the accounts. You need to complete your requirements.
1.1.3.2.5 Members should be able to follow other members.

**Comment by batuhancanli0** [comment]
problems  have been fixed according to given feedback [requirements](https://github.com/bounswe/bounswe2024group4/wiki/Requirements)
