### ISSUE TITLE
Fix the problems in non-functional requirements.

### ISSUE THREAD

**Issue by zbuseaydin** [bounswe/bounswe2024group4#97]
### Issue Type

Other

### Issue Description

Fix the problems in the [non-functional requirements](https://github.com/bounswe/bounswe2024group4/wiki/Requirements#2-non-functional-requirements) according to the feedback given.

### Additional Context

Feedback:

### Non-Functional
- Some of your requirements have variables.
2.2.1 The platform shall support at least [specific number] user accounts without performance degradation.
2.4.2 The platform shall comply with modern Secure Sockets Layer (SSL) requirements, including [specify requirements, e.g., TLS 1.2 or higher].

- What is the response ?
2.2.2 The system shall respond to user requests within at most [specific time, e.g., 3] seconds under normal operating conditions.

**Comment by nucan25** [comment]
Necessary arrangements have been made. [Non-functional 
  Requirements](https://github.com/bounswe/bounswe2024group4/wiki/Requirements#2-non-functional-requirements)
