### ISSUE TITLE
Design the sign up and login pages for mobile

### ISSUE THREAD

**Issue by zbuseaydin** [bounswe/bounswe2024group4#99]
### Issue Type

Other

### Issue Description

Design the sign up and login pages for mobile in Figma

**Comment by talhaordukaya** [comment]
Designs are finished [here](https://www.figma.com/file/Fe4AFtLTvBMo3FkuAtHZgr/NBAForum?type=design&node-id=0%3A1&mode=design&t=mS0CLLrPZFQ4Eloq-1).
